### ISSUE TITLE
Error: [Error: Socket Closed] 

### ISSUE THREAD

**Issue by 6pm** [talmobi/tor-request#3]
I have error: [Error: Socket Closed]
 
My Code: 
`var tr = require('tor-request');
tr.request('https://api.ipify.org', function (err, res, body) {
    console.log(err);
});`

**Comment by talmobi** [comment]
Hello!

I should add better errors. This happens because you don't have a tor client running. It's listed as a requirement: https://github.com/talmobi/tor-request#requirements

If you're using any kind of unix you should be able to install tor from your package manager. Such as "apt-get install tor" (debian) or "brew install tor" (OSX).

With windows you have to download the expert bundle and run tor.exe.

This is all explained under the requirements title in the README: https://github.com/talmobi/tor-request#requirements
