### ISSUE TITLE
multi instances of tor

### ISSUE THREAD

**Issue by sajjad-ser** [talmobi/tor-request#35]
hi 
how can i use multi instances of tor-request with multi instances of tor?

**Comment by talmobi** [comment]
The module assumed you're only connecting to a single tor client. Not exactly sure why you would want to connect to multiple ones at the same time (usually you're connecting to your own tor client which handles all the actual tor related networking details).

You could spawn child processes or fork and wrap the code with an create/init function that.

The crux of your problem is that the tor client configuration (address, password, port) are mutable and "global" to the module once it's required (so you don't have to pass an instance around across multiple files): https://github.com/talmobi/tor-request/blob/ae9b25835f852dbaf5cbb58949dca7cb3b71e34d/index.js#L315-L318

But, like I said, not sure why this is desirable or practical (you only run one tor client locally that you connect to).

**Comment by sajjad-ser** [comment]
tanks
