### ISSUE TITLE
 Uncaught Error: ip has not changed after new tor session was requested.

### ISSUE THREAD

**Issue by bavuongco10** [talmobi/tor-request#9]
Currently you package have not pass all of your test.
1) Testing request and tor-request against http://api.ipify.org request a new tor session with tr.newTorSession should return without error:
Uncaught Error: connect ECONNREFUSED 127.0.0.1:9051
Testing request and tor-request against http://api.ipify.org verify that we have a new tor session (new ip) should return without error:
Uncaught Error: ip has not changed after new tor session was requested.

And that should be a problem if we want to change ip for every request we make!
Can you fix this?

**Comment by talmobi** [comment]
Hello!

It seems to work fine! Did you configure and enable the Tor ControlPort (It's optional, but needed if you want to get a new IP address to use programmatically without restarting your tor client).

see the README.md here: https://github.com/talmobi/tor-request#optional-configuring-tor-enabling-the-controlport

I should edit and clarify the test and add better error messages for this case, though.

**Comment by bavuongco10** [comment]
yeah, it the best i you can just specify the test more, and change the code a little so that the test can pass! Thanks you and keep up the good work!

**Comment by talmobi** [comment]
You're right. Since configuring the ControlPort is optional and not required to use tor, the primary test should probably reflect this. Pushed a commit to separate the primary tests and the optional tests.

(it's only handy if you want to programmatically refrsh your tor session by talking to tor directly - as opposed to restarting tor in order to get a new session)
